#!/usr/bin/env bash

set -euxo pipefail

out_file=api/v1alpha1/zz_subscription_types.go
generated_code_warning="// Code generated by quicktype. DO NOT EDIT.\n\n"

rm -rf ${out_file}

quicktype \
  --src-lang schema --alphabetize-properties \
  --lang go --just-types-and-package --package v1alpha1 --omit-empty \
  -o ${out_file} \
  pkg/subscription/schemas/*.json

printf "${generated_code_warning}$(cat ${out_file})" > ${out_file}

# Pointers to bools and strings don't make a lot of sense in most cases.
#
# Note that -i works on Linux, but not on macOS. -i '' works on macOS, but not
# on Linux. So we use -i.bak, which works on both.
sed -i.bak 's/\*string/string/g' ${out_file}
# As of right now, this transformation is ok, but we can revisit it if we ever
# need nullable numbers or non-int numbers.
sed -i.bak 's/\*int64/int64/g' ${out_file}
sed -i.bak 's/\*CommitSelectionStrategy/CommitSelectionStrategy/g' ${out_file}
sed -i.bak 's/\*ImageSelectionStrategy/ImageSelectionStrategy/g' ${out_file}
sed -i.bak 's/NewestFromBranch[[:space:]]*CommitSelectionStrategy/CommitSelectionStrategyNewestFromBranch CommitSelectionStrategy/' ${out_file}
sed -i.bak 's/NewestTag[[:space:]]*CommitSelectionStrategy/CommitSelectionStrategyNewestTag CommitSelectionStrategy/' ${out_file}
sed -i.bak 's/Digest[[:space:]]*ImageSelectionStrategy/ImageSelectionStrategyDigest ImageSelectionStrategy/' ${out_file}
sed -i.bak 's/NewestBuild[[:space:]]*ImageSelectionStrategy/ImageSelectionStrategyNewestBuild ImageSelectionStrategy/' ${out_file}
sed -i.bak 's/CacheByTag[[:space:]]*\*bool/CacheByTag bool/' ${out_file}
sed -i.bak 's/InsecureSkipTLSVerify[[:space:]]*\*bool/InsecureSkipTLSVerify bool/' ${out_file}
# Move the Alias field (comment + declaration) to the end of each struct so
# go-to-protobuf assigns existing fields their original numbers and Alias
# gets the next available number without shifting anything.
awk '
/\/\/ Alias is an optional/ { alias_block = $0 "\n"; in_alias = 1; next }
in_alias { alias_block = alias_block $0 "\n"; if (/Alias[[:space:]]+string/) in_alias = 0; next }
/^}/ && alias_block != "" { printf "%s", alias_block; alias_block = ""; print; next }
{ print }
' ${out_file} > ${out_file}.tmp && mv ${out_file}.tmp ${out_file}

rm ${out_file}.bak

gofmt -w ${out_file}
